# 服务端口配置
server:
  port: 8080
  servlet:
    context-path: /

# dubbo配置
dubbo:
  application:
    name: api-gateway-consumer
  registry:
    protocol: zookeeper
    address: 
  monitor:
    protocol: registry
  config-center:
    address: 
    timeout: 10000
  consumer:
    check: false

# 日志级别、存储位置
logging:
  level:
    root: info
  file:
    name: log/gateway.log