# 服务端口配置
server:
  port: 8070
  servlet:
    context-path: /

# 数据源
spring:
  datasource:
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 
    type: com.alibaba.druid.pool.DruidDataSource
  # redis配置
  redis:
    port: 
    host: 
    password: 
    lettuce:
      pool:
        max-active: 10
        max-idle: 6
        max-wait: 5000

# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  # entity alias
  type-aliases-package: org.microservice.pub.commons.entity




# dubbo配置
dubbo:
  application:
    name: display-provider
  registry:
    protocol: zookeeper
    address: 
  monitor:
    protocol: registry
  config-center:
    address: 
    timeout: 10000
  protocol:
    id: display_service
    name: dubbo
    port: -1

# 日志级别、存储位置
logging:
  level:
    root: info
  file:
    name: log/display.log