# 服务端口配置
server:
  port: 8070
  servlet:
    context-path: /

# 数据源
spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sacc_book?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    type: com.alibaba.druid.pool.DruidDataSource

# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  # entity alias
  type-aliases-package: org.microservice.pub.commons.entity


# dubbo配置
dubbo:
  application:
    name: display-provider
  registry:
    protocol: zookeeper
    address: 123.57.35.204:2181
  monitor:
    protocol: registry
  config-center:
    address: zookeeper://123.57.35.204:2181
    timeout: 10000
  protocol:
    id: display_service
    name: dubbo
    port: -1

# 日志级别、存储位置
logging:
  level:
    root: info
  file:
    name: log/display.log