# 服务端口配置
server:
  port: 8060
  servlet:
    context-path: /

# 数据源配置
spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sacc_book?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT

# 日志级别、存储位置
logging:
  level:
    root: info
  file:
    name: log/recommend.log